# Generated by Django 3.1 on 2020-08-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_eventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
