# Generated by Django 3.1 on 2020-08-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfclub',
            name='price_table',
        ),
    ]
