# Generated by Django 3.1 on 2020-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='info',
            field=models.JSONField(blank=True, null=True, verbose_name='Course info'),
        ),
    ]
