# Generated by Django 3.1 on 2020-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='multiple_booking_orders',
            field=models.PositiveIntegerField(default=1, verbose_name='Multiple booking orders'),
        ),
    ]
