# Generated by Django 3.1 on 2020-08-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineusermembership',
            unique_together=set(),
        ),
    ]
