# Generated by Django 3.1.1 on 2020-09-19 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfClubStaffMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=True, verbose_name='Primary')),
                ('permission_manage_booking', models.BooleanField(default=True, verbose_name='Can manage booking')),
                ('permission_view_sales', models.BooleanField(default=False, verbose_name='Can view sales')),
                ('permission_change_settings', models.BooleanField(default=False, verbose_name='Can change settings')),
                ('golf_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Golf club staff membership',
                'verbose_name_plural': 'Golf club staff membership',
            },
        ),
    ]
