# Generated by Django 3.1 on 2020-08-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='customer_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.customergroup', verbose_name='Default customer group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lineuser',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='LineUserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.customergroup', verbose_name='Customer group')),
                ('golf_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club')),
                ('line_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.lineuser', verbose_name='Line user')),
            ],
            options={
                'verbose_name': 'Line user membership',
                'verbose_name_plural': 'Line user membership',
                'unique_together': {('golf_club', 'line_user')},
            },
        ),
    ]
