# Generated by Django 3.1 on 2020-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='hole',
            field=models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='max_pax',
            field=models.IntegerField(default=4, verbose_name='Max PAX'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='weekdays_max_in_advance',
            field=models.IntegerField(db_index=True, default=30, verbose_name='Weekdays maximum in advance'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='weekdays_min_in_advance',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Weekdays minimum in advance'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='weekend_max_in_advance',
            field=models.IntegerField(db_index=True, default=7, verbose_name='Weekend maximum in advance'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='weekend_min_in_advance',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Weekend minimum in advance'),
        ),
    ]
