# Generated by Django 3.1 on 2020-09-05 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfBookingOrderStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_status', models.IntegerField(choices=[(0, 'Booking open'), (1, 'Booking confirmed'), (2, 'Booking offered'), (3, 'Booking accepted'), (4, 'Booking closed')], db_index=True, default=0, verbose_name='Order status')),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Refund requests'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfbookingorder', verbose_name='Golf booking order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Golf booking order status log',
                'verbose_name_plural': 'Golf booking order status logs',
            },
        ),
    ]
