# Generated by Django 3.1 on 2020-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Confirmed'), (2, 'Offered'), (3, 'Accepted'), (4, 'Closed')], db_index=True, default=0, verbose_name='Order status'),
        ),
        migrations.AddField(
            model_name='golfbookingorder',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
    ]
