# Generated by Django 3.1 on 2020-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='line_notify_access_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='LINE notify access token'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='line_bot_channel_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LINE bot channel access token'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='line_bot_channel_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='LINE bot channel secret'),
        ),
    ]
