# Generated by Django 3.1.1 on 2020-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingorder',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Invisible after unfollow'),
        ),
    ]
