# Generated by Django 3.1 on 2020-09-13 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiffApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('app_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='LIFF ID')),
                ('title', models.CharField(max_length=255, verbose_name='LIFF title')),
                ('end_point_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Endpoint URL')),
                ('golf_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club')),
            ],
            options={
                'verbose_name': 'LIFF app',
                'verbose_name_plural': 'LIFF apps',
                'unique_together': {('golf_club', 'title')},
            },
        ),
    ]
