# Generated by Django 3.1 on 2020-08-30 09:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfBookingOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='product name')),
                ('list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='list price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='selling price')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfbookingorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Golf booking order product',
                'verbose_name_plural': 'Golf booking order products',
            },
        ),
    ]
