# Generated by Django 3.1 on 2020-08-09 09:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('line_user_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='LINE user ID')),
                ('follow_status', models.IntegerField(choices=[(0, 'Unfollow'), (1, 'Follow')], db_index=True, default=1, verbose_name='Follow status')),
                ('fullname', models.CharField(blank=True, max_length=32, verbose_name='Fullname')),
            ],
            options={
                'verbose_name': 'LINE user',
                'verbose_name_plural': 'LINE users',
            },
        ),
    ]
