# Generated by Django 3.1 on 2020-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfclub',
            name='info',
        ),
        migrations.AddField(
            model_name='golfclub',
            name='info_flex_message',
            field=models.JSONField(blank=True, null=True, verbose_name='Course info flex message'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='order_flex_message',
            field=models.JSONField(blank=True, null=True, verbose_name='Order flex message'),
        ),
    ]
