# Generated by Django 3.1.1 on 2020-09-21 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfBookingOrderTimeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('round_time', models.TimeField(db_index=True, verbose_name='Round time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfbookingorder', verbose_name='Golf booking order')),
            ],
            options={
                'verbose_name': 'Golf booking order tee time offer',
                'verbose_name_plural': 'Golf booking order tee time offers',
            },
        ),
    ]
