# Generated by Django 3.1 on 2020-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='liff',
            field=models.JSONField(blank=True, null=True, verbose_name='LIFF'),
        ),
        migrations.DeleteModel(
            name='Liff',
        ),
    ]
