# Generated by Django 3.1 on 2020-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200831_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbookingorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Booking open'), (1, 'Booking confirmed'), (2, 'Booking offered'), (3, 'Booking accepted'), (4, 'Booking closed')], db_index=True, default=0, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='working_status',
            field=models.IntegerField(choices=[(0, 'Course open'), (1, 'Course closed'), (2, 'Suspended')], db_index=True, default=0, verbose_name='Working status'),
        ),
    ]
