# Generated by Django 3.1 on 2020-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingorder_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbookingorder',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Refund requests'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
    ]
