# Generated by Django 3.1 on 2020-08-22 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_remove_golfclub_price_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('list_price', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee list price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee selling price')),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.customergroup', verbose_name='Customer group')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.season', verbose_name='Season')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.timeslot', verbose_name='Timeslot')),
            ],
            options={
                'verbose_name': 'Green fee',
                'verbose_name_plural': 'Green fee',
            },
        ),
        migrations.AddField(
            model_name='golfclub',
            name='caddie_compulsory',
            field=models.IntegerField(choices=[(0, 'Optional'), (1, 'Compulsory')], db_index=True, default=1, verbose_name='Caddie compulsory'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='cart_compulsory',
            field=models.IntegerField(choices=[(0, 'Optional'), (1, 'Compulsory'), (2, 'Compulsory 2 player+'), (3, 'Compulsory 3 player+'), (4, 'Compulsory 4 player+'), (5, 'Compulsory 5 player+'), (6, 'Compulsory 6 player+')], db_index=True, default=0, verbose_name='Cart compulsory'),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
