# Generated by Django 3.1 on 2020-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200826_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='line_user_id',
            field=models.CharField(db_index=True, max_length=48, unique=True, verbose_name='LINE user ID'),
        ),
    ]
