# Generated by Django 3.1 on 2020-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfclub_multiple_booking_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='caddie_selling_price',
            new_name='caddie_fee_selling_price',
        ),
    ]
