# Generated by Django 3.1 on 2020-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfclub_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfclub',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Course info'),
        ),
    ]
