# Generated by Django 3.1 on 2020-08-30 10:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingorderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfbookingorderproduct',
            name='title',
        ),
        migrations.AddField(
            model_name='golfbookingorderproduct',
            name='product',
            field=models.IntegerField(choices=[(0, 'Green fee'), (1, 'Caddie fee'), (2, 'Cart fee')], db_index=True, default=0, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderproduct',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='List price'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfbookingorder', verbose_name='Golf booking order'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Selling price'),
        ),
    ]
