# Generated by Django 3.1.1 on 2020-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingorder_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='line_rich_menu',
            field=models.JSONField(blank=True, null=True, verbose_name='LINE rich menu'),
        ),
    ]
