# Generated by Django 3.1 on 2020-09-09 17:15

from django.db import migrations, models
import golf.models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfclub_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail image'),
        ),
    ]
