# Generated by Django 3.1.1 on 2020-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingordertimeoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbookingorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Booking offered'), (1, 'Booking accepted'), (2, 'Booking open'), (3, 'Booking confirmed'), (4, 'Booking closed')], db_index=True, default=2, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='golfbookingorder',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Refund requests'), (2, 'Paid'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderstatuslog',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Booking offered'), (1, 'Booking accepted'), (2, 'Booking open'), (3, 'Booking confirmed'), (4, 'Booking closed')], db_index=True, default=2, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderstatuslog',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Refund requests'), (2, 'Paid'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
    ]
