# Generated by Django 3.1 on 2020-09-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingpromotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfbookingpromotion',
            old_name='customer_group',
            new_name='condition_customer_group',
        ),
    ]
