# Generated by Django 3.1 on 2020-08-11 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200811_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('app_name', models.CharField(db_index=True, max_length=48, verbose_name='LIFF app name')),
                ('liff_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='LIFF ID')),
                ('endpoint_url', models.URLField(verbose_name='Endpoint URL')),
                ('golf_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club')),
            ],
            options={
                'verbose_name': 'LIFF',
                'verbose_name_plural': 'LIFF',
                'unique_together': {('golf_club', 'app_name')},
            },
        ),
    ]
