# Generated by Django 3.1.1 on 2020-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfclubstaffmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='staffs',
            field=models.ManyToManyField(db_index=True, through='golf.GolfClubStaffMembership', to='golf.GolfClub', verbose_name='Golf club staffs'),
        ),
    ]
