# Generated by Django 3.1 on 2020-08-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_lineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='golf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='line_user_id',
            field=models.CharField(db_index=True, max_length=48, verbose_name='LINE user ID'),
        ),
        migrations.AlterUniqueTogether(
            name='lineuser',
            unique_together={('line_user_id', 'golf_club')},
        ),
    ]
