# Generated by Django 3.1 on 2020-09-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfbookingorderstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfclub',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.customergroup', verbose_name='Default customer group'),
        ),
    ]
