# Generated by Django 3.1 on 2020-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200826_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='category',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Member guest'), (2, 'Visitor')], db_index=True, default=2, verbose_name='Member categories'),
        ),
    ]
