# Generated by Django 3.1 on 2020-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200912_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbookingorder',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Paid'), (2, 'Refund requests'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='golfbookingorderstatuslog',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not paid'), (1, 'Paid'), (2, 'Refund requests'), (3, 'Refunded')], db_index=True, default=0, verbose_name='Payment status'),
        ),
    ]
