# Generated by Django 3.1 on 2020-08-30 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200830_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingorder',
            name='cart',
            field=models.IntegerField(default=0, verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='golfbookingorder',
            name='pax',
            field=models.IntegerField(default=1, verbose_name='PAX'),
        ),
        migrations.AddField(
            model_name='golfbookingorder',
            name='round_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Round date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfbookingorder',
            name='round_time',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Round time'),
            preserve_default=False,
        ),
    ]
