# Generated by Django 3.1 on 2020-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='min_pax',
            field=models.IntegerField(default=1, verbose_name='Min PAX'),
        ),
    ]
