# Generated by Django 3.1 on 2020-09-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200901_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='cart_selling_price',
            new_name='cart_fee_selling_price',
        ),
    ]
