# Generated by Django 3.1 on 2020-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200822_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfee',
            name='list_price',
            field=models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='List price'),
        ),
        migrations.AlterField(
            model_name='greenfee',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Selling price'),
        ),
    ]
