# Generated by Django 3.1.1 on 2020-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_golfclub_line_rich_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='liffapp',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('th', 'Thai'), ('ko', 'Korean')], default='en', max_length=16, verbose_name='Language'),
        ),
    ]
