# Generated by Django 3.1 on 2020-09-10 02:26

from django.db import migrations, models
import golf.models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_golfclub_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingpromotion',
            name='banner',
            field=models.ImageField(blank=True, upload_to=golf.models.promotion_upload_directory_path, verbose_name='Promotion banner image'),
        ),
    ]
