# Generated by Django 3.1 on 2020-08-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200820_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week'),
        ),
    ]
