# Generated by Django 3.1 on 2020-09-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_rightssupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Staff right',
                'verbose_name_plural': 'Staff rights',
                'permissions': (('manage_booking', 'Manage booking'), ('view_sales', 'View sales'), ('change_settings', 'Change settings')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='RightsSupport',
        ),
    ]
