# Generated by Django 3.1 on 2020-08-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200826_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineusermembership',
            name='line_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.lineuser', verbose_name='LINE user'),
        ),
    ]
