# Generated by Django 3.1 on 2020-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20200809_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='LINE display name'),
        ),
    ]
