# Generated by Django 3.1 on 2020-08-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200831_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingorderproduct',
            name='customer_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.customergroup', verbose_name='Customer group'),
            preserve_default=False,
        ),
    ]
