# Generated by Django 3.1 on 2020-08-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200817_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfclub',
            name='info',
            field=models.JSONField(blank=True, null=True, verbose_name='Course info'),
        ),
    ]
