# Generated by Django 3.1 on 2020-08-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_area_district_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.district', verbose_name='District'),
            preserve_default=False,
        ),
    ]
