# Generated by Django 3.1 on 2020-09-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200914_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffright',
            options={'default_permissions': (), 'managed': False, 'permissions': (('manage_booking', 'Can manage booking'), ('view_sales', 'Can view sales'), ('change_settings', 'Can change settings')), 'verbose_name': 'Staff right', 'verbose_name_plural': 'Staff rights'},
        ),
    ]
