# Generated by Django 3.1 on 2020-08-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200820_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='golf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='golf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='golf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club'),
            preserve_default=False,
        ),
    ]
