# Generated by Django 3.1 on 2020-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200822_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='caddie_fee_list_price',
            field=models.DecimalField(decimal_places=2, default=400, help_text='THB', max_digits=11, verbose_name='Caddie fee list price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='caddie_selling_price',
            field=models.DecimalField(decimal_places=2, default=900, help_text='THB', max_digits=11, verbose_name='Caddie fee selling price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='cart_fee_list_price',
            field=models.DecimalField(decimal_places=2, default=900, help_text='THB', max_digits=11, verbose_name='Cart fee list price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='cart_selling_price',
            field=models.DecimalField(decimal_places=2, default=900, help_text='THB', max_digits=11, verbose_name='Cart fee selling price'),
            preserve_default=False,
        ),
    ]
