# Generated by Django 3.1 on 2020-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200808_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfclub',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Longitude'),
        ),
    ]
