# Generated by Django 3.1.1 on 2020-10-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_liffapp_lang'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liffapp',
            unique_together={('golf_club', 'title', 'lang')},
        ),
    ]
