# Generated by Django 3.1 on 2020-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_customergroup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='weekend_booking_on_monday',
            field=models.BooleanField(default=False, verbose_name='Weekend booking on Monday'),
        ),
    ]
