# Generated by Django 3.1 on 2020-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20200912_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='no_order_flex_message',
            field=models.JSONField(blank=True, null=True, verbose_name='No order flex message'),
        ),
    ]
