# Generated by Django 3.1 on 2020-08-29 19:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0005_golfclub_weekend_booking_on_monday'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfBookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Order no')),
                ('fullname', models.CharField(blank=True, max_length=64, verbose_name='Fullname')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-agent')),
                ('accept_language', models.TextField(blank=True, verbose_name='Accept-language')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('total_list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Total list price')),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Total selling price')),
                ('line_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.lineuser', verbose_name='LINE user')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf.golfbookingorder', verbose_name='Parent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Golf booking order',
                'verbose_name_plural': 'Golf booking orders',
            },
        ),
    ]
