# Generated by Django 3.1 on 2020-08-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_auto_20200820_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='golf_club',
        ),
    ]
