# Generated by Django 3.1 on 2020-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_auto_20200817_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='scorecard',
            field=models.JSONField(blank=True, null=True, verbose_name='Scorecard'),
        ),
    ]
