# Generated by Django 3.1 on 2020-08-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_golfbookingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfbookingorder',
            name='golf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.golfclub', verbose_name='Golf club'),
            preserve_default=False,
        ),
    ]
