# Generated by Django 3.1 on 2020-08-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_remove_rate_golf_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='price_table',
            field=models.JSONField(blank=True, null=True, verbose_name='Price table'),
        ),
    ]
